In [1]:
import pandas as pd 
import os
# Set the maximum number of rows and columns to display
pd.set_option('display.max_rows', 200)  # Adjust this number as needed
pd.set_option('display.max_columns', 50)  # Adjust this number as needed

In [2]:
# Specify the folder path 
folder_path = '../../data_CityEvent/processed/events_cbgid_by_category/'

# List all files in the folder
file_names = os.listdir(folder_path)

file_names.remove('unscheduled_intermediate') 
file_names.remove('archive_before_dropping_missing_geometry') 
# Print the file names
for file_name in file_names:
    print(file_name)

attended_community.csv
attended_concerts.csv
attended_conferences.csv
attended_expos.csv
attended_festivals.csv
attended_performing-arts.csv
attended_sports.csv
non_attended_academic.csv
non_attended_daylight-savings.csv
non_attended_observances.csv
non_attended_politics.csv
non_attended_public-holidays.csv
non_attended_school-holidays.csv
unscheduled_airport-delays.csv
unscheduled_disasters.csv
unscheduled_health-warnings.csv
unscheduled_severe-weather.csv
unscheduled_terror.csv

In [3]:
for file_name in file_names:
    current_df = pd.read_csv(f'{folder_path}/{file_name}')
    print(f'{file_name}: {current_df.shape}')

attended_community.csv: (35060, 36)
attended_concerts.csv: (96444, 36)
attended_conferences.csv: (10407, 36)
attended_expos.csv: (5381, 36)
attended_festivals.csv: (8490, 36)
attended_performing-arts.csv: (29042, 36)
attended_sports.csv: (16271, 36)
non_attended_academic.csv: (5275, 36)
non_attended_daylight-savings.csv: (6, 36)
non_attended_observances.csv: (1282, 36)
non_attended_politics.csv: (6, 36)
non_attended_public-holidays.csv: (96, 36)
non_attended_school-holidays.csv: (13027, 36)
unscheduled_airport-delays.csv: (475296, 36)
unscheduled_disasters.csv: (7444, 36)
unscheduled_health-warnings.csv: (543, 36)
unscheduled_severe-weather.csv: (147794, 36)
unscheduled_terror.csv: (1859, 36)

In [4]:
import os
import pandas as pd
from utils.time.convert_to_datetime import convert_to_datetime

earliest_time = None
latest_time = None


for file_name in file_names:
    current_df = pd.read_csv(os.path.join(folder_path, file_name))
    print(f'{file_name}: {current_df.shape}')

    # current_df = convert_to_datetime(current_df)
    # print(type(current_df['EVENT_START_BOSTON'][0]))

    datetime_columns = ['EVENT_START_BOSTON','EVENT_END_BOSTON']
    for datetime_column in datetime_columns:
        # Convert the specified columns to datetime format
        current_df[datetime_column] = pd.to_datetime(current_df[datetime_column], errors='coerce')

    # get min and max times
    curr_earliest_time = current_df['EVENT_START_BOSTON'].min()
    curr_latest_time = current_df['EVENT_START_BOSTON'].max()

    print(f"File: {file_name} | Earliest: {curr_earliest_time} | Latest: {curr_latest_time}")
    
    # Update the earliest and latest time across all files
    if earliest_time is None or (curr_earliest_time < earliest_time):
        earliest_time = curr_earliest_time
    if latest_time is None or (curr_latest_time > latest_time):
        latest_time = curr_latest_time

print('Final Results:')
print(f'Earliest Time: {earliest_time}, Latest Time: {latest_time}')

attended_community.csv: (35060, 36)
File: attended_community.csv | Earliest: 2020-03-02 20:00:00 | Latest: 2023-10-15 01:00:00
attended_concerts.csv: (96444, 36)
File: attended_concerts.csv | Earliest: 2020-05-20 05:00:00 | Latest: 2023-10-15 03:00:00
attended_conferences.csv: (10407, 36)
File: attended_conferences.csv | Earliest: 2020-05-20 19:00:00 | Latest: 2023-10-14 21:30:00
attended_expos.csv: (5381, 36)
File: attended_expos.csv | Earliest: 2020-06-04 19:00:00 | Latest: 2023-10-14 21:00:00
attended_festivals.csv: (8490, 36)
File: attended_festivals.csv | Earliest: 2020-06-04 06:30:00 | Latest: 2023-10-15 03:00:00
attended_performing-arts.csv: (29042, 36)
File: attended_performing-arts.csv | Earliest: 2020-03-01 07:00:00 | Latest: 2023-10-15 03:00:00
attended_sports.csv: (16271, 36)
File: attended_sports.csv | Earliest: 2020-05-30 10:00:00 | Latest: 2023-10-15 00:00:00
non_attended_academic.csv: (5275, 36)
File: non_attended_academic.csv | Earliest: 2020-01-21 11:00:00 | Latest: 2023-10-14 10:00:00
non_attended_daylight-savings.csv: (6, 36)
File: non_attended_daylight-savings.csv | Earliest: 2020-11-01 06:00:00 | Latest: 2023-03-12 07:00:00
non_attended_observances.csv: (1282, 36)
File: non_attended_observances.csv | Earliest: 2020-05-19 03:00:00 | Latest: 2023-10-15 03:00:00
non_attended_politics.csv: (6, 36)
File: non_attended_politics.csv | Earliest: 2020-11-03 03:00:00 | Latest: 2022-12-06 03:00:00
non_attended_public-holidays.csv: (96, 36)
File: non_attended_public-holidays.csv | Earliest: 2020-05-25 03:00:00 | Latest: 2023-10-09 03:00:00
non_attended_school-holidays.csv: (13027, 36)
File: non_attended_school-holidays.csv | Earliest: 2020-05-16 03:00:00 | Latest: 2023-10-14 03:00:00
unscheduled_airport-delays.csv: (475296, 36)
File: unscheduled_airport-delays.csv | Earliest: 2020-05-17 12:00:00 | Latest: 2023-07-17 01:30:00
unscheduled_disasters.csv: (7444, 36)
File: unscheduled_disasters.csv | Earliest: 2020-05-18 10:00:00 | Latest: 2023-07-18 00:00:00
unscheduled_health-warnings.csv: (543, 36)
File: unscheduled_health-warnings.csv | Earliest: 2020-03-15 10:00:00 | Latest: 2023-07-15 22:37:44
unscheduled_severe-weather.csv: (147794, 36)
File: unscheduled_severe-weather.csv | Earliest: 2020-04-24 02:46:00 | Latest: 2023-07-18 20:00:00
unscheduled_terror.csv: (1859, 36)
File: unscheduled_terror.csv | Earliest: 2020-05-18 10:30:00 | Latest: 2023-07-16 11:30:00
Final Results:
Earliest Time: 2020-01-21 11:00:00, Latest Time: 2023-10-15 03:00:00

In [5]:
print('Final Results:')
print(f'Earliest Time: {earliest_time}, Latest Time: {latest_time}')

Final Results:
Earliest Time: 2020-01-21 11:00:00, Latest Time: 2023-10-15 03:00:00

In [56]:
test_before = pd.read_csv('../../data_CityEvent/processed/events_cbgid_by_category/unscheduled_severe-weather.csv')
test_before.shape

(151229, 36)

In [57]:
test_before.head()

,EVENT_ID,CREATE_DT,UPDATE_DT,TITLE,CATEGORY,LABELS,DESCRIPTION,EVENT_START,EVENT_END,PREDICTED_END,TIMEZONE,ENTITIES,GEO,IMPACT_PATTERNS,SCOPE,PLACEKEY,COUNTRY_CODE,PLACE_HIERARCHIES,PHQ_ATTENDANCE,PHQ_RANK,LOCAL_RANK,AVIATION_RANK,STATUS,BRAND_SAFE,PARENT_EVENT_ID,PREDICTED_EVENT_SPEND_ACCOMMODATION,PREDICTED_EVENT_SPEND_HOSPITALITY,PREDICTED_EVENT_SPEND_TRANSPORTATION,ROW_INSERTED_DT,ROW_UPDATED_DT,EVENT_START_BOSTON,EVENT_END_BOSTON,PREDICTED_END_BOSTON,NEW_TIMEZONE,geometry,GEOID
0,x8gFNWwgeSvekgRcT5,2023-07-10 19:45:21.919,2023-07-11 01:09:18.042,Severe Thunderstorm,severe-weather,"[""storm"",""thunderstorm"",""weather"",""weather-war...",This is the detail for a severe weather event ...,2023-07-10 19:40:00,2023-07-11 01:00:00.000,NaN,America/Chicago,NaN,"{'coordinates': [[[-101.09039306599999, 37.736...","[{""impact_type"":""phq_rank"",""impacts"":[{""date_l...",county,NaN,US,"[[""6295630"",""6255149"",""6252001"",""4273857"",""544...",NaN,56,NaN,NaN,active,True,NaN,NaN,NaN,NaN,2023-07-10 20:30:12.509,2023-07-11 01:30:06.828,2023-07-10 20:40:00,2023-07-11 02:00:00,NaN,America/New_York,NaN,NaN
1,Faa6BLLh2UzuXVYQw6,2021-11-12 14:45:17.813,2022-01-20 01:55:46.369,Flood,severe-weather,"[""flood"",""weather"",""weather-warning""]",This is the detail for a severe weather event ...,2021-11-12 22:27:00,2021-11-14 15:07:00.000,NaN,America/Los_Angeles,NaN,"{'coordinates': [[[-121.96, 47.56], [-122.0399...","[{""impact_type"":""phq_rank"",""impacts"":[{""date_l...",county,NaN,US,"[[""6295630"",""6255149"",""6252001"",""5815135"",""579...",NaN,86,NaN,NaN,active,True,NaN,NaN,NaN,NaN,2022-12-21 04:54:20.629,2023-01-31 20:57:26.060,2021-11-13 01:27:00,2021-11-14 18:07:00,NaN,America/New_York,NaN,NaN
2,EsoPU84qGSubmjZqGa,2020-10-11 23:42:04.074,2022-03-04 23:18:56.142,Severe Thunderstorm,severe-weather,"[""storm"",""thunderstorm"",""weather"",""weather-war...",This is the detail for a severe weather event ...,2020-10-12 03:40:00,2020-10-12 06:00:00.000,NaN,America/Chicago,NaN,"{'coordinates': [[[[-95.30849456799996, 39.999...","[{""impact_type"":""phq_rank"",""impacts"":[{""date_l...",county,NaN,US,"[[""6295630"",""6255149"",""6252001"",""4398678"",""505...",NaN,56,NaN,NaN,active,True,NaN,NaN,NaN,NaN,2022-12-21 04:54:20.629,2023-01-31 20:57:26.060,2020-10-12 04:40:00,2020-10-12 07:00:00,NaN,America/New_York,NaN,NaN
3,52pZo7KrxsCubr8br9,2022-01-13 19:45:45.111,2022-03-04 23:11:30.030,Air Stagnation,severe-weather,"[""air-quality"",""weather"",""weather-warning""]",This is the detail for a severe weather event ...,2022-01-18 21:22:00,2022-01-21 18:00:00.000,NaN,America/Boise,NaN,"{'coordinates': [[[-115.03779602099996, 42.526...","[{""impact_type"":""phq_rank"",""impacts"":[{""date_l...",county,NaN,US,"[[""6295630"",""6255149"",""6252001"",""5596512"",""558...",NaN,65,NaN,NaN,active,True,NaN,NaN,NaN,NaN,2022-12-21 04:54:20.629,2023-01-31 20:57:26.060,2022-01-18 23:22:00,2022-01-21 20:00:00,NaN,America/New_York,NaN,NaN
4,G9oxj5r8vDUSJ6JdxK,2021-06-25 23:31:15.335,2022-01-24 21:04:35.103,Severe Thunderstorm,severe-weather,"[""storm"",""thunderstorm"",""weather"",""weather-war...",This is the detail for a severe weather event ...,2021-06-26 00:01:00,2021-06-26 00:15:00.000,NaN,America/Chicago,NaN,"{'coordinates': [[[-101.2, 39.72], [-101.31, 3...","[{""impact_type"":""phq_rank"",""impacts"":[{""date_l...",county,NaN,US,"[[""6295630"",""6255149"",""6252001"",""4273857"",""544...",NaN,86,NaN,NaN,active,True,NaN,NaN,NaN,NaN,2022-12-21 04:54:20.629,2023-01-31 20:57:26.060,2021-06-26 01:01:00,2021-06-26 01:15:00,NaN,America/New_York,NaN,NaN

In [ ]:
# EVENT_ID, CBGID / GEOID, geometry, EVENT_START_BOSTON, EVENT_END_BOSTON, CATEGORY

In [48]:
# import pandas as pd

# def hour_rows_df(df):
#     # Convert the EVENT_START_BOSTON and EVENT_END_BOSTON to datetime
#     datetime_columns = ['EVENT_START_BOSTON','EVENT_END_BOSTON']
#     for datetime_column in datetime_columns:
#         # Convert the specified columns to datetime format
#         df[datetime_column] = pd.to_datetime(df[datetime_column], errors='coerce')

#     columns_to_keep = ['EVENT_ID', 'GEOID', 'geometry', 'EVENT_START_BOSTON', 'EVENT_END_BOSTON', 'CATEGORY']
#     df = df[columns_to_keep]

#     # Define a function to create a range of hourly timestamps between start and end times
#     def create_hourly_rows(row):
#         return pd.date_range(start=row['EVENT_START_BOSTON'], end=row['EVENT_END_BOSTON'], freq='H')

#     # Apply the function to each row and store the result in a new column 'hourly_times'
#     df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

#     # Now explode the DataFrame to create one row per hour
#     expanded_df = df.explode('hourly_times')

#     # Print the result
#     print(expanded_df.shape)

#     return expanded_df

#     # expanded_df.to_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/f.csv')

In [6]:
import pandas as pd

def hour_rows_df(df):
    # Convert the EVENT_START_BOSTON and EVENT_END_BOSTON to datetime
    datetime_columns = ['EVENT_START_BOSTON', 'EVENT_END_BOSTON']
    for datetime_column in datetime_columns:
        # Convert the specified columns to datetime format
        df[datetime_column] = pd.to_datetime(df[datetime_column], errors='coerce')

    columns_to_keep = ['EVENT_ID', 'GEOID', 'geometry', 'EVENT_START_BOSTON', 'EVENT_END_BOSTON', 'CATEGORY']
    df = df[columns_to_keep]

    # Define a function to create a range of hourly timestamps between start and end times
    def create_hourly_rows(row):
        start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
        end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
        return pd.date_range(start=start_time, end=end_time, freq='H')

    # Apply the function to each row and store the result in a new column 'hourly_times'
    df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

    # Explode the DataFrame to create one row per hour
    expanded_df = df.explode('hourly_times')

    # Print the result shape (optional)
    # print(expanded_df.shape)

    return expanded_df

In [7]:
import os
import pandas as pd
# count = 0
for file_name in file_names:
    current_df = pd.read_csv(os.path.join(folder_path, file_name))
    print(f'{file_name}: {current_df.shape}')

    datetime_columns = ['EVENT_START_BOSTON', 'EVENT_END_BOSTON']
    for datetime_column in datetime_columns:
        # Convert the specified columns to datetime format
        current_df[datetime_column] = pd.to_datetime(current_df[datetime_column], errors='coerce')
        # print(datetime_column)
        # print(current_df[datetime_column].isna().sum())

    # Drop rows with NaN (or NaT) in any of the datetime columns
    current_df.dropna(subset=datetime_columns, inplace=True)

    # Check the shape after dropping rows with NaT values
    print(f'{file_name} after dropping NaT: {current_df.shape}')

    current_df_hourly = hour_rows_df(current_df)
    
    file_name = file_name[:-4]
    current_df_hourly.to_csv(f'../../data_CityEvent/processed/hourly_events_cbgid_category/{file_name}_hourly.csv', index=False)
    # count += 1
    # if count == 4:
    #     break

attended_community.csv: (35060, 36)
attended_community.csv after dropping NaT: (35059, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

attended_concerts.csv: (96444, 36)
attended_concerts.csv after dropping NaT: (96444, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

attended_conferences.csv: (10407, 36)
attended_conferences.csv after dropping NaT: (10407, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

attended_expos.csv: (5381, 36)
attended_expos.csv after dropping NaT: (5381, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

attended_festivals.csv: (8490, 36)
attended_festivals.csv after dropping NaT: (8490, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

attended_performing-arts.csv: (29042, 36)
attended_performing-arts.csv after dropping NaT: (29042, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

attended_sports.csv: (16271, 36)
attended_sports.csv after dropping NaT: (16269, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

non_attended_academic.csv: (5275, 36)
non_attended_academic.csv after dropping NaT: (5275, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

non_attended_daylight-savings.csv: (6, 36)
non_attended_daylight-savings.csv after dropping NaT: (6, 36)
non_attended_observances.csv: (1282, 36)
non_attended_observances.csv after dropping NaT: (1282, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

non_attended_politics.csv: (6, 36)
non_attended_politics.csv after dropping NaT: (6, 36)
non_attended_public-holidays.csv: (96, 36)
non_attended_public-holidays.csv after dropping NaT: (96, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

non_attended_school-holidays.csv: (13027, 36)
non_attended_school-holidays.csv after dropping NaT: (13027, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

unscheduled_airport-delays.csv: (475296, 36)
unscheduled_airport-delays.csv after dropping NaT: (475296, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

unscheduled_disasters.csv: (7444, 36)
unscheduled_disasters.csv after dropping NaT: (7444, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

unscheduled_health-warnings.csv: (543, 36)
unscheduled_health-warnings.csv after dropping NaT: (543, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

unscheduled_severe-weather.csv: (147794, 36)
unscheduled_severe-weather.csv after dropping NaT: (147794, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

unscheduled_terror.csv: (1859, 36)
unscheduled_terror.csv after dropping NaT: (1859, 36)

C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  start_time = row['EVENT_START_BOSTON'].floor('H')  # Round down to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  end_time = row['EVENT_END_BOSTON'].ceil('H')  # Round up to nearest hour
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:17: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  return pd.date_range(start=start_time, end=end_time, freq='H')
C:\Users\HP\AppData\Local\Temp\ipykernel_5788\190740556.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly_times'] = df.apply(create_hourly_rows, axis=1)

In [10]:
# import os
# import pandas as pd

# for file_name in file_names:
#     current_df = pd.read_csv(os.path.join(folder_path, file_name))
#     print(f'{file_name}: {current_df.shape}')

#     current_df_hourly = hour_rows_df(current_df)

#     current_df_hourly.to_csv(f'../../data_CityEvent/processed/hourly_events_cbgid_category/{file_name}_hourly.csv')

In [11]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/attended_community_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,Q8qTSY8YLfHCpz65tE,60133390023,POINT (-122.064 37.9089),2021-12-04 06:00:00,2021-12-04 09:00:00,community,2021-12-04 06:00:00
1,Q8qTSY8YLfHCpz65tE,60133390023,POINT (-122.064 37.9089),2021-12-04 06:00:00,2021-12-04 09:00:00,community,2021-12-04 07:00:00
2,Q8qTSY8YLfHCpz65tE,60133390023,POINT (-122.064 37.9089),2021-12-04 06:00:00,2021-12-04 09:00:00,community,2021-12-04 08:00:00
3,Q8qTSY8YLfHCpz65tE,60133390023,POINT (-122.064 37.9089),2021-12-04 06:00:00,2021-12-04 09:00:00,community,2021-12-04 09:00:00
4,BrGhonYexS6JirL4g4,60372073012,POINT (-118.2474094 34.052744),2022-08-27 06:00:00,2022-08-27 06:00:00,community,2022-08-27 06:00:00

In [12]:
test['GEOID'].isna().sum()

np.int64(0)

In [13]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/attended_concerts_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,3frn7bSYiQcPFZofyU,60371907002,POINT (-118.3373827 34.0984237),2022-12-30 07:30:00,2022-12-30 07:30:00,concerts,2022-12-30 07:30:00
1,daYFMPdnBxJTqrRVBg,60110004003,POINT (-122.5445485 39.3750411),2021-04-03 04:00:00,2021-04-03 04:00:00,concerts,2021-04-03 04:00:00
2,CfosrLm2AE7cgXy5At,60759803001,POINT (-122.4862138 37.7694208),2023-05-28 21:00:00,2023-05-28 21:00:00,concerts,2023-05-28 21:00:00
3,A4RK8zK3Y33orKoVCy,60750124021,POINT (-122.4153062 37.778644),2022-11-27 06:00:00,2022-11-27 06:00:00,concerts,2022-11-27 06:00:00
4,H3KduZhpZCwSFe4Fyt,60371975001,POINT (-118.2604789 34.0776572),2021-11-17 06:00:00,2021-11-17 06:00:00,concerts,2021-11-17 06:00:00

In [14]:
test['GEOID'].isna().sum()

np.int64(0)

In [15]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/attended_conferences_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,6Bsv456a5wwUugPcgR,60730054001,POINT (-117.1624983 32.7071375),2021-06-02 19:00:00,2021-06-06 04:00:00,conferences,2021-06-02 19:00:00
1,6Bsv456a5wwUugPcgR,60730054001,POINT (-117.1624983 32.7071375),2021-06-02 19:00:00,2021-06-06 04:00:00,conferences,2021-06-02 20:00:00
2,6Bsv456a5wwUugPcgR,60730054001,POINT (-117.1624983 32.7071375),2021-06-02 19:00:00,2021-06-06 04:00:00,conferences,2021-06-02 21:00:00
3,6Bsv456a5wwUugPcgR,60730054001,POINT (-117.1624983 32.7071375),2021-06-02 19:00:00,2021-06-06 04:00:00,conferences,2021-06-02 22:00:00
4,6Bsv456a5wwUugPcgR,60730054001,POINT (-117.1624983 32.7071375),2021-06-02 19:00:00,2021-06-06 04:00:00,conferences,2021-06-02 23:00:00

In [16]:
test['GEOID'].isna().sum()

np.int64(0)

In [17]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/attended_expos_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,5XS7M6QQvPAYdscWYi,60190013013,POINT (-119.75099620000003 36.7315432),2022-03-19 19:00:00,2022-03-21 04:00:00,expos,2022-03-19 19:00:00
1,5XS7M6QQvPAYdscWYi,60190013013,POINT (-119.75099620000003 36.7315432),2022-03-19 19:00:00,2022-03-21 04:00:00,expos,2022-03-19 20:00:00
2,5XS7M6QQvPAYdscWYi,60190013013,POINT (-119.75099620000003 36.7315432),2022-03-19 19:00:00,2022-03-21 04:00:00,expos,2022-03-19 21:00:00
3,5XS7M6QQvPAYdscWYi,60190013013,POINT (-119.75099620000003 36.7315432),2022-03-19 19:00:00,2022-03-21 04:00:00,expos,2022-03-19 22:00:00
4,5XS7M6QQvPAYdscWYi,60190013013,POINT (-119.75099620000003 36.7315432),2022-03-19 19:00:00,2022-03-21 04:00:00,expos,2022-03-19 23:00:00

In [19]:
test['GEOID'].isna().sum()

np.int64(0)

In [20]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/attended_festivals_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,BjykLFcBAmgmw96g2K,60816063003,POINT (-122.32226454023922 37.56426260733782),2023-06-10 21:00:00,2023-06-11 03:00:00,festivals,2023-06-10 21:00:00
1,BjykLFcBAmgmw96g2K,60816063003,POINT (-122.32226454023922 37.56426260733782),2023-06-10 21:00:00,2023-06-11 03:00:00,festivals,2023-06-10 22:00:00
2,BjykLFcBAmgmw96g2K,60816063003,POINT (-122.32226454023922 37.56426260733782),2023-06-10 21:00:00,2023-06-11 03:00:00,festivals,2023-06-10 23:00:00
3,BjykLFcBAmgmw96g2K,60816063003,POINT (-122.32226454023922 37.56426260733782),2023-06-10 21:00:00,2023-06-11 03:00:00,festivals,2023-06-11 00:00:00
4,BjykLFcBAmgmw96g2K,60816063003,POINT (-122.32226454023922 37.56426260733782),2023-06-10 21:00:00,2023-06-11 03:00:00,festivals,2023-06-11 01:00:00

In [21]:
test['GEOID'].isna().sum()

np.int64(0)

In [22]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/attended_performing-arts_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,GPMA2jf6EFDiskAhqD,60371254012,POINT (-118.3737469 34.1646645),2021-10-29 07:30:00,2021-10-29 07:30:00,performing-arts,2021-10-29 07:30:00
1,5K8qbBDNqvGtiGyYGy,60373020021,POINT (-118.254095 34.148864),2023-04-30 06:00:00,2023-04-30 06:00:00,performing-arts,2023-04-30 06:00:00
2,F8dYhrwZ6cn9jdWMUy,60650301042,POINT (-117.3675233 33.999677),2023-07-13 03:00:00,2023-07-13 03:00:00,performing-arts,2023-07-13 03:00:00
3,CK4Zs8muwUSdTTLtnb,60014028002,POINT (-122.2672222 37.8113889),2022-04-17 06:00:00,2022-04-17 07:30:00,performing-arts,2022-04-17 06:00:00
4,CK4Zs8muwUSdTTLtnb,60014028002,POINT (-122.2672222 37.8113889),2022-04-17 06:00:00,2022-04-17 07:30:00,performing-arts,2022-04-17 07:00:00

In [23]:
test['GEOID'].isna().sum()

np.int64(0)

In [24]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/attended_sports_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,AUrj6Lke2fgubmAJT7,60710021091,POINT (-117.5662772 34.0728996),2023-03-05 05:00:00,2023-03-05 05:00:00,sports,2023-03-05 05:00:00
1,5Z4KbUY5FUtWVg8SYV,60372074001,POINT (-118.2436849 34.0522342),2022-04-02 19:00:00,2022-04-02 19:00:00,sports,2022-04-02 19:00:00
2,HGsBcLZcM8PiF8iLSt,60372312202,POINT (-118.2841482 34.01263819999999),2023-06-08 05:30:00,2023-06-08 07:38:44,sports,2023-06-08 05:30:00
3,HGsBcLZcM8PiF8iLSt,60372312202,POINT (-118.2841482 34.01263819999999),2023-06-08 05:30:00,2023-06-08 07:38:44,sports,2023-06-08 06:30:00
4,HGsBcLZcM8PiF8iLSt,60372312202,POINT (-118.2841482 34.01263819999999),2023-06-08 05:30:00,2023-06-08 07:38:44,sports,2023-06-08 07:30:00

In [25]:
test['GEOID'].isna().sum()

np.int64(0)

In [26]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/non_attended_academic_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,CgRQ2KdXw8A3bMV8Nb,60730085104,POINT (-117.1635759 32.8039378),2021-02-01 11:00:00,2021-05-29 09:59:59,academic,2021-02-01 11:00:00
1,CgRQ2KdXw8A3bMV8Nb,60730085104,POINT (-117.1635759 32.8039378),2021-02-01 11:00:00,2021-05-29 09:59:59,academic,2021-02-01 12:00:00
2,CgRQ2KdXw8A3bMV8Nb,60730085104,POINT (-117.1635759 32.8039378),2021-02-01 11:00:00,2021-05-29 09:59:59,academic,2021-02-01 13:00:00
3,CgRQ2KdXw8A3bMV8Nb,60730085104,POINT (-117.1635759 32.8039378),2021-02-01 11:00:00,2021-05-29 09:59:59,academic,2021-02-01 14:00:00
4,CgRQ2KdXw8A3bMV8Nb,60730085104,POINT (-117.1635759 32.8039378),2021-02-01 11:00:00,2021-05-29 09:59:59,academic,2021-02-01 15:00:00

In [27]:
test['GEOID'].isna().sum()

np.int64(0)

In [28]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/non_attended_daylight-savings_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,amL2Tyu6FS228Z3rFG,201259507005,POINT (-95.712891 37.09024),2023-03-12 07:00:00,2023-03-13 05:59:59,daylight-savings,2023-03-12 07:00:00
1,amL2Tyu6FS228Z3rFG,201259507005,POINT (-95.712891 37.09024),2023-03-12 07:00:00,2023-03-13 05:59:59,daylight-savings,2023-03-12 08:00:00
2,amL2Tyu6FS228Z3rFG,201259507005,POINT (-95.712891 37.09024),2023-03-12 07:00:00,2023-03-13 05:59:59,daylight-savings,2023-03-12 09:00:00
3,amL2Tyu6FS228Z3rFG,201259507005,POINT (-95.712891 37.09024),2023-03-12 07:00:00,2023-03-13 05:59:59,daylight-savings,2023-03-12 10:00:00
4,amL2Tyu6FS228Z3rFG,201259507005,POINT (-95.712891 37.09024),2023-03-12 07:00:00,2023-03-13 05:59:59,daylight-savings,2023-03-12 11:00:00

In [29]:
test['GEOID'].isna().sum()

np.int64(0)

In [30]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/non_attended_observances_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,yQ6zqRwD1d8d,201259507005,POINT (-95.712891 37.09024),2020-10-16 03:00:00,2020-10-17 02:59:59,observances,2020-10-16 03:00:00
1,yQ6zqRwD1d8d,201259507005,POINT (-95.712891 37.09024),2020-10-16 03:00:00,2020-10-17 02:59:59,observances,2020-10-16 04:00:00
2,yQ6zqRwD1d8d,201259507005,POINT (-95.712891 37.09024),2020-10-16 03:00:00,2020-10-17 02:59:59,observances,2020-10-16 05:00:00
3,yQ6zqRwD1d8d,201259507005,POINT (-95.712891 37.09024),2020-10-16 03:00:00,2020-10-17 02:59:59,observances,2020-10-16 06:00:00
4,yQ6zqRwD1d8d,201259507005,POINT (-95.712891 37.09024),2020-10-16 03:00:00,2020-10-17 02:59:59,observances,2020-10-16 07:00:00

In [31]:
test['GEOID'].isna().sum()

np.int64(0)

In [32]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/non_attended_politics_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,7CEUThPX4QvqYLZtHh,201259507005,POINT (-95.712891 37.09024),2022-12-06 03:00:00,2022-12-07 02:59:59,politics,2022-12-06 03:00:00
1,7CEUThPX4QvqYLZtHh,201259507005,POINT (-95.712891 37.09024),2022-12-06 03:00:00,2022-12-07 02:59:59,politics,2022-12-06 04:00:00
2,7CEUThPX4QvqYLZtHh,201259507005,POINT (-95.712891 37.09024),2022-12-06 03:00:00,2022-12-07 02:59:59,politics,2022-12-06 05:00:00
3,7CEUThPX4QvqYLZtHh,201259507005,POINT (-95.712891 37.09024),2022-12-06 03:00:00,2022-12-07 02:59:59,politics,2022-12-06 06:00:00
4,7CEUThPX4QvqYLZtHh,201259507005,POINT (-95.712891 37.09024),2022-12-06 03:00:00,2022-12-07 02:59:59,politics,2022-12-06 07:00:00

In [33]:
test['GEOID'].isna().sum()

np.int64(0)

In [34]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/non_attended_public-holidays_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,az48rA6wVhLjViwVbx,201259507005,POINT (-95.712891 37.09024),2022-11-24 03:00:00,2022-11-25 02:59:59,public-holidays,2022-11-24 03:00:00
1,az48rA6wVhLjViwVbx,201259507005,POINT (-95.712891 37.09024),2022-11-24 03:00:00,2022-11-25 02:59:59,public-holidays,2022-11-24 04:00:00
2,az48rA6wVhLjViwVbx,201259507005,POINT (-95.712891 37.09024),2022-11-24 03:00:00,2022-11-25 02:59:59,public-holidays,2022-11-24 05:00:00
3,az48rA6wVhLjViwVbx,201259507005,POINT (-95.712891 37.09024),2022-11-24 03:00:00,2022-11-25 02:59:59,public-holidays,2022-11-24 06:00:00
4,az48rA6wVhLjViwVbx,201259507005,POINT (-95.712891 37.09024),2022-11-24 03:00:00,2022-11-25 02:59:59,public-holidays,2022-11-24 07:00:00

In [35]:
test['GEOID'].isna().sum()

np.int64(0)

In [36]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/non_attended_school-holidays_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,8suPhiirmZmpD7drSY,60530147002,POINT (-121.72502188091119 36.77977076378298),2021-12-18 03:00:00,2022-01-10 02:59:59,school-holidays,2021-12-18 03:00:00
1,8suPhiirmZmpD7drSY,60530147002,POINT (-121.72502188091119 36.77977076378298),2021-12-18 03:00:00,2022-01-10 02:59:59,school-holidays,2021-12-18 04:00:00
2,8suPhiirmZmpD7drSY,60530147002,POINT (-121.72502188091119 36.77977076378298),2021-12-18 03:00:00,2022-01-10 02:59:59,school-holidays,2021-12-18 05:00:00
3,8suPhiirmZmpD7drSY,60530147002,POINT (-121.72502188091119 36.77977076378298),2021-12-18 03:00:00,2022-01-10 02:59:59,school-holidays,2021-12-18 06:00:00
4,8suPhiirmZmpD7drSY,60530147002,POINT (-121.72502188091119 36.77977076378298),2021-12-18 03:00:00,2022-01-10 02:59:59,school-holidays,2021-12-18 07:00:00

In [37]:
test['GEOID'].isna().sum()

np.int64(0)

In [38]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/unscheduled_airport-delays_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,WNgy97K76LxgUwb5Sb,21850003001,POINT (-148.464206 70.196561),2022-09-14 23:00:00,2022-09-15 03:30:00,airport-delays,2022-09-14 23:00:00
1,WNgy97K76LxgUwb5Sb,21850003001,POINT (-148.464206 70.196561),2022-09-14 23:00:00,2022-09-15 03:30:00,airport-delays,2022-09-15 00:00:00
2,WNgy97K76LxgUwb5Sb,21850003001,POINT (-148.464206 70.196561),2022-09-14 23:00:00,2022-09-15 03:30:00,airport-delays,2022-09-15 01:00:00
3,WNgy97K76LxgUwb5Sb,21850003001,POINT (-148.464206 70.196561),2022-09-14 23:00:00,2022-09-15 03:30:00,airport-delays,2022-09-15 02:00:00
4,WNgy97K76LxgUwb5Sb,21850003001,POINT (-148.464206 70.196561),2022-09-14 23:00:00,2022-09-15 03:30:00,airport-delays,2022-09-15 03:00:00

In [39]:
test['GEOID'].isna().sum()

np.int64(0)

In [40]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/unscheduled_disasters_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,Uvmd3Znm3fYB7UKRVU,300810002021,POINT (-114.01693074590078 46.58368479462088),2021-02-23 03:14:00,2021-02-24 03:00:00,disasters,2021-02-23 03:14:00
1,Uvmd3Znm3fYB7UKRVU,300810002021,POINT (-114.01693074590078 46.58368479462088),2021-02-23 03:14:00,2021-02-24 03:00:00,disasters,2021-02-23 04:14:00
2,Uvmd3Znm3fYB7UKRVU,300810002021,POINT (-114.01693074590078 46.58368479462088),2021-02-23 03:14:00,2021-02-24 03:00:00,disasters,2021-02-23 05:14:00
3,Uvmd3Znm3fYB7UKRVU,300810002021,POINT (-114.01693074590078 46.58368479462088),2021-02-23 03:14:00,2021-02-24 03:00:00,disasters,2021-02-23 06:14:00
4,Uvmd3Znm3fYB7UKRVU,300810002021,POINT (-114.01693074590078 46.58368479462088),2021-02-23 03:14:00,2021-02-24 03:00:00,disasters,2021-02-23 07:14:00

In [41]:
test['GEOID'].isna().sum()

np.int64(0)

In [42]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/unscheduled_health-warnings_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,Nsb7ofjShuaFj9Atkb,50510120011,POINT (-93.2523438 34.7490491),2020-05-26 06:00:00,2020-05-27 05:59:59,health-warnings,2020-05-26 06:00:00
1,Nsb7ofjShuaFj9Atkb,50510120011,POINT (-93.2523438 34.7490491),2020-05-26 06:00:00,2020-05-27 05:59:59,health-warnings,2020-05-26 07:00:00
2,Nsb7ofjShuaFj9Atkb,50510120011,POINT (-93.2523438 34.7490491),2020-05-26 06:00:00,2020-05-27 05:59:59,health-warnings,2020-05-26 08:00:00
3,Nsb7ofjShuaFj9Atkb,50510120011,POINT (-93.2523438 34.7490491),2020-05-26 06:00:00,2020-05-27 05:59:59,health-warnings,2020-05-26 09:00:00
4,Nsb7ofjShuaFj9Atkb,50510120011,POINT (-93.2523438 34.7490491),2020-05-26 06:00:00,2020-05-27 05:59:59,health-warnings,2020-05-26 10:00:00

In [43]:
test['GEOID'].isna().sum()

np.int64(0)

In [44]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/unscheduled_severe-weather_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,x8gFNWwgeSvekgRcT5,201879641001,POINT (-101.56512679819338 37.62451385628617),2023-07-10 20:40:00,2023-07-11 02:00:00,severe-weather,2023-07-10 20:40:00
1,x8gFNWwgeSvekgRcT5,201879641001,POINT (-101.56512679819338 37.62451385628617),2023-07-10 20:40:00,2023-07-11 02:00:00,severe-weather,2023-07-10 21:40:00
2,x8gFNWwgeSvekgRcT5,201879641001,POINT (-101.56512679819338 37.62451385628617),2023-07-10 20:40:00,2023-07-11 02:00:00,severe-weather,2023-07-10 22:40:00
3,x8gFNWwgeSvekgRcT5,201879641001,POINT (-101.56512679819338 37.62451385628617),2023-07-10 20:40:00,2023-07-11 02:00:00,severe-weather,2023-07-10 23:40:00
4,x8gFNWwgeSvekgRcT5,201879641001,POINT (-101.56512679819338 37.62451385628617),2023-07-10 20:40:00,2023-07-11 02:00:00,severe-weather,2023-07-11 00:40:00

In [45]:
test['GEOID'].isna().sum()

np.int64(0)

In [46]:
test = pd.read_csv('../../data_CityEvent/processed/hourly_events_cbgid_category/unscheduled_terror_hourly.csv')
test.head()

,EVENT_ID,GEOID,geometry,EVENT_START_BOSTON,EVENT_END_BOSTON,CATEGORY,hourly_times
0,a6pNDshreqWW6StmsG,530330265002,POINT (-122.3548035 47.5151346),2021-06-12 01:45:00,2021-06-12 01:55:00,terror,2021-06-12 01:45:00
1,F4K64ziNbvxEPnrGpt,180973703011,POINT (-86.322507 39.6824195),2021-04-16 03:00:00,2021-04-16 03:15:00,terror,2021-04-16 03:00:00
2,ftThTTBiQrkgRc6GD5,516600002072,POINT (-78.8770053 38.4220497),2022-10-16 04:00:00,2022-10-17 03:59:59,terror,2022-10-16 04:00:00
3,ftThTTBiQrkgRc6GD5,516600002072,POINT (-78.8770053 38.4220497),2022-10-16 04:00:00,2022-10-17 03:59:59,terror,2022-10-16 05:00:00
4,ftThTTBiQrkgRc6GD5,516600002072,POINT (-78.8770053 38.4220497),2022-10-16 04:00:00,2022-10-17 03:59:59,terror,2022-10-16 06:00:00

In [47]:
test['GEOID'].isna().sum()

np.int64(0)

In [22]:
# Below is testing