In [2]:
import pandas as pd
import os
# Set the maximum number of rows and columns to display
pd.set_option('display.max_rows', 200)  # Adjust this number as needed
pd.set_option('display.max_columns', 50)  # Adjust this number as needed

In [4]:
mob = pd.read_csv('../../data_CityEvent/SafeGraph/Neighborhood_Patterns_US-0-DATE_RANGE_START-2018-01-01.csv.gz')
mob.shape

(2878536, 4)

In [5]:
mob.head()

   Unnamed: 0       BGFIPS                 Date  Visit
0           0  60750479014  2018-01-01 00:00:00     23
1           1  60374800123  2018-01-01 00:00:00     62
2           2  60650414073  2018-01-01 00:00:00     34
3           3  60330006004  2018-01-01 00:00:00     10
4           4  60890119004  2018-01-01 00:00:00     32

In [3]:
community = pd.read_csv('../../data_CityEvent/processed/events_cbgid_by_category/attended_community.csv')
community.shape

(35082, 36)

In [6]:
display(community.head())

,EVENT_ID,CREATE_DT,UPDATE_DT,TITLE,CATEGORY,LABELS,DESCRIPTION,EVENT_START,EVENT_END,PREDICTED_END,TIMEZONE,ENTITIES,GEO,IMPACT_PATTERNS,SCOPE,PLACEKEY,COUNTRY_CODE,PLACE_HIERARCHIES,PHQ_ATTENDANCE,PHQ_RANK,LOCAL_RANK,AVIATION_RANK,STATUS,BRAND_SAFE,PARENT_EVENT_ID,PREDICTED_EVENT_SPEND_ACCOMMODATION,PREDICTED_EVENT_SPEND_HOSPITALITY,PREDICTED_EVENT_SPEND_TRANSPORTATION,ROW_INSERTED_DT,ROW_UPDATED_DT,EVENT_START_BOSTON,EVENT_END_BOSTON,PREDICTED_END_BOSTON,NEW_TIMEZONE,geometry,GEOID
0,Q8qTSY8YLfHCpz65tE,2021-09-03 08:04:29.232,2022-11-09 04:53:56.426,Total Distortion (Social Distortion Tribute) L...,community,"[""concert"",""music""]",Total Distortion (Social Distortion Tribute) L...,2021-12-04 03:00:00,2021-12-04 06:00:00.000,NaN,America/Los_Angeles,"[{""entity_id"":""bsfXBRVjhRmkfcjHe6s8yw"",""format...","{'coordinates': [-122.064, 37.9089], 'type': '...",NaN,locality,zzw-224@5vg-9jj-zpv,US,"[[""6295630"",""6255149"",""6252001"",""5332921"",""533...",243.0,38,57,NaN,active,True,NaN,NaN,NaN,NaN,2022-12-21 04:54:20.629,2023-01-31 20:57:26.060,2021-12-04 06:00:00,2021-12-04 09:00:00,NaN,America/New_York,POINT (-122.064 37.9089),6.013339e+10
1,BrGhonYexS6JirL4g4,2022-08-14 00:54:10.292,2022-11-08 04:48:13.915,"The Space Cadettes, Ryan Rice, and Villain Royale",community,"[""concert"",""music""]",NaN,2022-08-27 03:00:00,2022-08-27 03:00:00.000,NaN,America/Los_Angeles,"[{""entity_id"":""SBYyinf7F6YR5brE3hVy8m"",""format...","{'coordinates': [-118.2474094, 34.052744], 'ty...",NaN,locality,226-222@5z5-3rr-skf,US,"[[""6295630"",""6255149"",""6252001"",""5332921"",""536...",150.0,34,44,NaN,active,True,NaN,NaN,NaN,NaN,2022-12-21 04:54:20.629,2023-01-31 20:57:26.060,2022-08-27 06:00:00,2022-08-27 06:00:00,NaN,America/New_York,POINT (-118.2474094 34.052744),6.037207e+10
2,DjYPceRuynZjB9jaM4,2022-11-09 20:26:02.893,2023-04-17 07:38:13.489,Club 90's,community,"[""concert"",""music""]",NaN,2022-11-19 06:00:00,2022-11-19 06:00:00.000,NaN,America/Los_Angeles,"[{""entity_id"":""gpBuZWSQjpyCrMSEQq6ym"",""formatt...","{'coordinates': [-118.2742751, 34.0838383], 't...",NaN,locality,22f@5z5-3p5-qzz,US,"[[""6295630"",""6255149"",""6252001"",""5332921"",""536...",840.0,48,60,NaN,active,True,NaN,NaN,NaN,NaN,2022-12-21 04:54:20.629,2023-04-17 12:30:24.086,2022-11-19 09:00:00,2022-11-19 09:00:00,NaN,America/New_York,POINT (-118.2742751 34.0838383),6.037196e+10
3,kNMDNBJHwjAf2uP5WF,2020-06-25 03:25:57.836,2022-03-21 23:42:45.221,“LAUNCH” with Host CASEY LEE “TWIST” and DJ ER,community,"[""concert"",""music"",""social""]",“LAUNCH” with Host CASEY LEE “TWIST” and DJ ER...,2020-11-06 05:00:00,2020-11-06 05:00:00.000,NaN,America/Los_Angeles,"[{""entity_id"":""HedCBJtivzvaKDZiHqCasu"",""format...","{'coordinates': [-118.3642232, 34.1376094], 't...",NaN,locality,NaN,US,"[[""6295630"",""6255149"",""6252001"",""5332921"",""536...",22.0,17,36,NaN,active,True,NaN,NaN,NaN,NaN,2022-12-21 04:54:20.629,2023-01-31 20:57:26.060,2020-11-06 08:00:00,2020-11-06 08:00:00,NaN,America/New_York,POINT (-118.3642232 34.1376094),6.037144e+10
4,62hNsK6AiADKcDBQMz,2020-03-12 05:03:24.320,2022-11-20 10:46:25.069,Math Games,community,"[""community"",""family""]",Practice problem solving and math skills while...,2020-12-06 23:00:00,2020-12-06 23:00:00.000,NaN,America/Los_Angeles,NaN,"{'coordinates': [-122.2277104, 37.4838384], 't...",NaN,locality,@5vh-7y5-5fz,US,"[[""6295630"",""6255149"",""6252001"",""5332921"",""539...",22.0,17,31,NaN,active,True,NaN,NaN,NaN,NaN,2022-12-21 04:54:20.629,2023-01-31 20:57:26.060,2020-12-07 02:00:00,2020-12-07 02:00:00,NaN,America/New_York,POINT (-122.2277104 37.4838384),6.081610e+10